from nids.ml.features.cicflow_style import CicFlowFeatures
from nids.ml.features.nsl_kdd_style import NslKddStyleFeatures


def make_record(**overrides) -> NslKddStyleFeatures:
    base = dict(
        duration=0.1,
        protocol_type="tcp",
        service="http",
        flag="SF",
        src_bytes=200,
        dst_bytes=1000,
        land=False,
        wrong_fragment=0,
        urgent=0,
        count=1,
        srv_count=1,
        serror_rate=0.0,
        srv_serror_rate=0.0,
        rerror_rate=0.0,
        srv_rerror_rate=0.0,
        same_srv_rate=1.0,
        diff_srv_rate=0.0,
        srv_diff_host_rate=0.0,
        dst_host_count=1,
        dst_host_srv_count=1,
        dst_host_same_srv_rate=1.0,
        dst_host_diff_srv_rate=0.0,
        dst_host_same_src_port_rate=0.0,
        dst_host_srv_diff_host_rate=0.0,
        dst_host_serror_rate=0.0,
        dst_host_srv_serror_rate=0.0,
        dst_host_rerror_rate=0.0,
        dst_host_srv_rerror_rate=0.0,
        src_ip="10.0.0.1",
        dst_ip="10.0.0.2",
        src_port=5000,
        dst_port=80,
    )
    base.update(overrides)
    return NslKddStyleFeatures(**base)


def make_cicflow_record(**overrides) -> CicFlowFeatures:
    base = dict(
        src_ip="10.0.0.1",
        dst_ip="10.0.0.2",
        src_port=5000,
        dst_port=80,
        protocol="tcp",
        flow_duration=100.0,
        tot_fwd_pkts=1,
        tot_bwd_pkts=1,
        totlen_fwd_pkts=100,
        totlen_bwd_pkts=100,
        fwd_pkt_len_max=100.0,
        fwd_pkt_len_min=100.0,
        fwd_pkt_len_mean=100.0,
        fwd_pkt_len_std=0.0,
        bwd_pkt_len_max=100.0,
        bwd_pkt_len_min=100.0,
        bwd_pkt_len_mean=100.0,
        bwd_pkt_len_std=0.0,
        flow_byts_per_s=1.0,
        flow_pkts_per_s=1.0,
        flow_iat_mean=0.0,
        flow_iat_std=0.0,
        flow_iat_max=0.0,
        flow_iat_min=0.0,
        fwd_iat_tot=0.0,
        fwd_iat_mean=0.0,
        fwd_iat_std=0.0,
        fwd_iat_max=0.0,
        fwd_iat_min=0.0,
        bwd_iat_tot=0.0,
        bwd_iat_mean=0.0,
        bwd_iat_std=0.0,
        bwd_iat_max=0.0,
        bwd_iat_min=0.0,
        fwd_psh_flags=0,
        bwd_psh_flags=0,
        fwd_urg_flags=0,
        bwd_urg_flags=0,
        fwd_header_len=40,
        bwd_header_len=40,
        fwd_pkts_per_s=1.0,
        bwd_pkts_per_s=1.0,
        pkt_len_min=100.0,
        pkt_len_max=100.0,
        pkt_len_mean=100.0,
        pkt_len_std=0.0,
        pkt_len_var=0.0,
        fin_flag_cnt=0,
        syn_flag_cnt=0,
        rst_flag_cnt=0,
        psh_flag_cnt=0,
        ack_flag_cnt=0,
        urg_flag_cnt=0,
        cwe_flag_cnt=0,
        ece_flag_cnt=0,
        down_up_ratio=1.0,
        pkt_size_avg=100.0,
        fwd_seg_size_avg=100.0,
        bwd_seg_size_avg=100.0,
        subflow_fwd_pkts=1.0,
        subflow_fwd_byts=100.0,
        subflow_bwd_pkts=1.0,
        subflow_bwd_byts=100.0,
        init_fwd_win_byts=64240,
        init_bwd_win_byts=29200,
        fwd_act_data_pkts=1,
        fwd_seg_size_min=100.0,
        active_mean=0.0,
        active_std=0.0,
        active_max=0.0,
        active_min=0.0,
        idle_mean=0.0,
        idle_std=0.0,
        idle_max=0.0,
        idle_min=0.0,
    )
    base.update(overrides)
    return CicFlowFeatures(**base)
